server:
  port: 18900

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security_demo
    username: root
    password: joe_jok5231
  jpa:
    show-sql: true

logging:
  level:
    org.springframework.web: INFO
    org.springframework.security: DEBUG
    com.example.security: DEBUG
  file:
    name: log/app.log
  pattern:
    file: '%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level --- [%15thread] %logger{50} : %msg%n'
