server:
  port: 18900

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security_demo?serverTimezone=UTC
    username: root
    password: joe_jok5231
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    com.example.security: DEBUG
    com.example: DEBUG
  config: classpath:logback_config.xml

selfDefine:
  logfile:
    rootPath: ./logs
    maxSize: 100MB