server:
  port: 18900



spring:
  datasource:
    name: druidDataSource
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/security_demo?useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=utf-8
    username: root
    password: root
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      filters: stat, wall, slf4j, config
      max-active: 100
      initial-size: 1
      max-wait: 60000
      min-idle: 1
      time-between-eviction-runs-millis: 3000000
      validation-query: select 'x'
      test--while-idle: true
      test-on-borrow: false
      test-on-return: false
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  output:
    ansi:
      enabled: always

logging:
  level:
    org.springframework.web: INFO
    org.springframework.security: DEBUG
    com.example.security: DEBUG
  file:
    name: log/app.log
  pattern:
    file: '%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level --- [%15thread] %logger{50} : %msg%n'
